//
//  ProjectRootDetector.swift
//  Again Cleaner
//
//  Pure (filesystem-free) rules for "is this a project?" and "is this folder a
//  recognised build artifact?". Used by the developer-junk scanner and tests.
//  A directory named `build` / `target` / `dist` is NOT junk unless a nearby
//  marker proves it belongs to a known build system.
//

import Foundation

enum ProjectRootDetector {

    /// Files/folders that identify a software project root.
    nonisolated static let rootMarkers: [String] = [
        ".git",
        "package.json",
        "Cargo.toml",
        "Podfile",
        "build.gradle",
        "build.gradle.kts",
        "settings.gradle",
        "settings.gradle.kts",
        "Package.swift",
        "CMakeLists.txt",
        "pubspec.yaml",
        "composer.json",
        "go.mod",
        "pyproject.toml",
        "Makefile",
    ]

    /// Folder-name suffixes that are Xcode project bundles.
    nonisolated static let rootSuffixes: [String] = [
        ".xcodeproj",
        ".xcworkspace",
    ]

    /// Artifact names that are proof enough wherever they appear.
    nonisolated static let unambiguousArtifacts: Set<String> = [
        "node_modules",
        "__pycache__",
        ".venv", ".tox", ".pytest_cache", ".mypy_cache", ".ruff_cache",
        ".next", ".nuxt", ".turbo", ".parcel-cache", ".angular",
        "_build",
        ".dart_tool",
        "Pods",
        "DerivedData",
    ]

    /// Ambiguous folder names → marker files that must exist in the parent
    /// (or, for Android module `build` / `.cxx`, the grandparent).
    nonisolated static let artifactMarkers: [String: [String]] = [
        "target": ["Cargo.toml"],
        "build": ["build.gradle", "build.gradle.kts", "settings.gradle",
                  "settings.gradle.kts", "CMakeLists.txt", "package.json",
                  "pubspec.yaml", "Makefile"],
        "dist": ["package.json", "pyproject.toml", "setup.py"],
        "out": ["package.json", "CMakeLists.txt"],
        "vendor": ["composer.json", "go.mod"],
        ".build": ["Package.swift"],
        ".cxx": ["build.gradle", "build.gradle.kts", "CMakeLists.txt"],
        ".gradle": ["build.gradle", "build.gradle.kts", "settings.gradle",
                    "settings.gradle.kts"],
    ]

    /// Names that also accept a marker one level further up (Android `app/build`).
    nonisolated static let allowGrandparentMarkers: Set<String> = [
        "build", ".cxx", ".gradle",
    ]

    nonisolated static func isProjectRoot(contents: [String]) -> Bool {
        let set = Set(contents)
        if rootMarkers.contains(where: { set.contains($0) }) { return true }
        return contents.contains { name in
            rootSuffixes.contains { name.hasSuffix($0) }
        }
    }

    nonisolated static func listingContainsMarkers(_ listing: [String], markers: [String]) -> Bool {
        let set = Set(listing)
        return markers.contains { set.contains($0) }
            || listing.contains { name in rootSuffixes.contains { name.hasSuffix($0) } }
    }

    /// Whether `name` under a parent (and optional grandparent) listing is a
    /// recognised, regenerable build artifact.
    nonisolated static func isValidArtifact(
        name: String,
        parentContents: [String],
        childContents: [String] = [],
        grandparentContents: [String] = []
    ) -> Bool {
        if unambiguousArtifacts.contains(name) || name.hasPrefix("cmake-build-") {
            return true
        }
        if name == "venv" || name == ".venv" {
            return childContents.contains("pyvenv.cfg")
        }
        if name == "bin" || name == "obj" {
            return parentContents.contains {
                $0.hasSuffix(".csproj") || $0.hasSuffix(".fsproj") || $0.hasSuffix(".vbproj")
            }
        }
        guard let markers = artifactMarkers[name] else { return false }
        if listingContainsMarkers(parentContents, markers: markers) { return true }
        if allowGrandparentMarkers.contains(name) {
            return listingContainsMarkers(grandparentContents, markers: markers)
        }
        return false
    }

    /// Human-readable type + why + how to regenerate. Used in the UI.
    nonisolated static func explanation(forArtifact name: String) -> (type: String, why: String, recovery: String) {
        switch name {
        case "node_modules":
            return ("Node.js dependencies",
                    "JavaScript/TypeScript packages installed by npm, yarn, pnpm or bun. Source files are not stored here.",
                    "Restore with `npm install`, `yarn`, `pnpm install` or `bun install` in the project.")
        case "target":
            return ("Rust target directory",
                    "Compiled artifacts generated by Cargo. Source files are not stored here. Cargo will rebuild it when needed.",
                    "Run `cargo build` in the project.")
        case "build":
            return ("Project build output",
                    "Generated by Gradle, CMake, Flutter or a JS bundler. Identified because a project marker sits next to it.",
                    "Rebuild the project with its usual build command.")
        case "dist", "out":
            return ("Bundled build output",
                    "Generated frontend/native output. Identified by a nearby package.json or CMakeLists.txt.",
                    "Rebuild the project.")
        case ".next", ".nuxt", ".turbo", ".parcel-cache", ".angular":
            return ("JS framework cache",
                    "Framework-generated cache and build output. Safe to remove; the next build recreates it.",
                    "Run the project's build or dev command.")
        case "Pods":
            return ("CocoaPods",
                    "Installed CocoaPods dependencies. The Podfile is the source of truth.",
                    "Run `pod install` in the project.")
        case "__pycache__", ".pytest_cache", ".mypy_cache", ".ruff_cache":
            return ("Python cache",
                    "Bytecode and tool caches. Regenerated on the next run.",
                    "Re-run the Python tool or interpreter.")
        case ".venv", "venv":
            return ("Python virtualenv",
                    "Isolated Python environment for this project. Recreated from requirements/pyproject.",
                    "Recreate with `python -m venv` and reinstall dependencies.")
        case ".dart_tool":
            return ("Dart/Flutter tool cache",
                    "Generated by the Dart toolchain. Source lives in the project, not here.",
                    "Run `dart pub get` or `flutter pub get`.")
        case "DerivedData":
            return ("In-project Xcode DerivedData",
                    "Build intermediates Xcode stores next to the project.",
                    "Xcode rebuilds on the next build.")
        case ".cxx":
            return ("Android native build",
                    "CMake/NDK generated native objects for an Android module.",
                    "Rebuild the Android module.")
        case ".gradle":
            return ("Project Gradle cache",
                    "Per-project Gradle cache (not ~/.gradle). Regenerated on the next Gradle run.",
                    "Run `./gradlew` in the project.")
        case "vendor":
            return ("Vendor directory",
                    "PHP Composer or Go vendor tree identified by composer.json / go.mod.",
                    "Run `composer install` or `go mod vendor`.")
        default:
            return ("Build artifact",
                    "Recognised generated output of a known build system. Source files are not stored here.",
                    "Rebuild the project.")
        }
    }
}
